#docker-compose -f docker-compose-dev.yml up --build
services:
  projectedb:
    image: postgres:14.8
    ports:
      - "5401:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}}
      - POSTGRES_USER=${POSTGRES_USER}}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}}