#docker-compose -f docker-compose-prod.yml up --build
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL={$SPRING_DATASOURCE_URL}}
      - SPRING_DATASOURCE_USERNAME={$SPRING_DATASOURCE_USERNAME}}
      - SPRING_DATASOURCE_PASSWORD={$SPRING_DATASOURCE_PASSWORD}}
  db:
    image: postgres:14.8
    ports:
      - "5401:5432"
    environment:
      - POSTGRES_DB={$POSTGRES_DB}}
      - POSTGRES_USER={$POSTGRES_USER}}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD}}